name: Fix

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # cancel-in-progress: true

jobs:
  fix:
    name: Fix
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 20
          cache-dependency-path: ./pnpm-lock.yaml
      - name: Install Dependencies
        run: pnpm install
      - name: Type Check
        run: pnpm run check
      - name: Lint
        run: pnpm run lint:fix
      - name: Run Tests
        run: pnpm run test:ci
      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
      - name: Commit Changes
        run: if [ -n "$(git status --porcelain)" ]; then git commit -a -m "Fix lint automatically" && git push origin; else echo "no changes"; fi
